services:
  rabbitscout:
    build: .
    ports:
      - "3000:3000"
    environment:
      - RABBITMQ_HOST=${RABBITMQ_HOST:-localhost}
      - RABBITMQ_PORT=${RABBITMQ_PORT:-15672}
      - RABBITMQ_PROTOCOL=${RABBITMQ_PROTOCOL:-http}
